const { v4 } = require("uuid");
 
const categories = [
  {
    id: '0880c241-d0f3-463a-83a3-9745b67eb884',
    name: "Sports",
  },
  {
    id: 'b08c0467-c931-48c1-8f17-42f964bc5119',
    name: "Geography",
  },
  {
    id: '150b5c13-9aee-4ae0-8ba9-967910f07541',
    name: "History",
  },
];
 
const difficulty = [
  {
    id: 'd98a3dd1-dbf8-4e76-918e-03f58bcb1cb4',
    name: "easy",
  },
  {
    id: 'd326b2cc-b7a2-4c45-a3c9-64acf236938a',
    name: "medium",
  },
  {
    id: '4158fd19-5900-492a-bb19-03ffd0749cfb',
    name: "hard",
  },
];
 
const questions = [
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question:
      "Which modern country is known as &quot;The Graveyard of Empires&quot;?",
    correctAnswer: "Afghanistan",
    incorrectAnswers: ["China", "Iraq", "Russia"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question: "What was William Frederick Cody better known as?",
    correctAnswer: "Buffalo Bill",
    incorrectAnswers: ["Billy the Kid", "Wild Bill Hickok", "Pawnee Bill"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question:
      "During WWII, in 1945, the United States dropped atomic bombs on the two Japanese cities of Hiroshima and what other city?",
    correctAnswer: "Nagasaki",
    incorrectAnswers: ["Kawasaki", "Tokyo", "Kagoshima"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question:
      "The &quot;Trail of Tears&quot; was a result of which United States President&#039;s Indian Removal Policy?",
    correctAnswer: "Andrew Jackson",
    incorrectAnswers: [
      "Harry S. Truman",
      "Martin Van Buren",
      "John Quincy Adams",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question: "Who discovered Penicillin?",
    correctAnswer: "Alexander Flemming",
    incorrectAnswers: ["Marie Curie", "Alfred Nobel", "Louis Pasteur"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question: "How was Socrates executed?",
    correctAnswer: "Poison",
    incorrectAnswers: ["Decapitation", "Firing squad", "Crucifixion "],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question: "When was Google founded?",
    correctAnswer: "September 4, 1998",
    incorrectAnswers: [
      "October 9, 1997",
      "December 12, 1989",
      "Feburary 7th, 2000",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question:
      "Which of the following African countries was most successful in resisting colonization?",
    correctAnswer: "Ethiopia",
    incorrectAnswers: ["C&ocirc;te d&rsquo;Ivoire", "Congo", "Namibia"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question:
      "In 1939, Britain and France declared war on Germany after it invaded which country?",
    correctAnswer: "Poland",
    incorrectAnswers: ["Czechoslovakia", "Austria", "Hungary"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question: "What country joined the EU in 2013?",
    correctAnswer: "Croatia",
    incorrectAnswers: ["Bulgaria", "Slovenia", "Turkey"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question:
      "What does the United States of America celebrate during the 4th of July?",
    correctAnswer: "The signing of the Declaration of Independence",
    incorrectAnswers: [
      "The anniversary of the Battle of Gettysburg",
      "The crossing of the Delaware River",
      "The ratification of the Constitution",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question: "Who was the first American in space?",
    correctAnswer: "Alan Shephard",
    incorrectAnswers: ["Neil Armstrong", "John Glenn", "Jim Lovell"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question:
      "Who was among those killed in the 2010 Smolensk, Russia plane crash tragedy?",
    correctAnswer: "The Polish President",
    incorrectAnswers: ["Pope John Paul II", "Bang-Ding Ow", "Albert Putin"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question:
      "Abolitionist John Brown raided the arsenal in which Virginia Town?",
    correctAnswer: "Harper&#039;s Ferry",
    incorrectAnswers: ["Richmond", "Harrisonburg", "Martinsburg"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question:
      "Which of the following countries was not an axis power during World War II?",
    correctAnswer: " Soviet Union",
    incorrectAnswers: ["Italy", "Germany", "Japan"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question: "Who was the first president of the United States?",
    correctAnswer: "George Washington",
    incorrectAnswers: ["James Madison", "Thomas Jefferson", "James K. Polk"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question:
      "What was the name commonly given to the ancient trade routes that connected the East and West of Eurasia?",
    correctAnswer: "Silk Road",
    incorrectAnswers: ["Spice Road", "Clay Road", "Salt Road"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question: "In what year was the M1911 pistol designed?",
    correctAnswer: "1911",
    incorrectAnswers: ["1907", "1899", "1917"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question: "In what year did the Wall Street Crash take place?",
    correctAnswer: "1929",
    incorrectAnswers: ["1932", "1930", "1925"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[2].id,
    question:
      "Who was the Prime Minister of Japan when Japan declared war on the US?",
    correctAnswer: "Hideki Tojo",
    incorrectAnswers: [
      "Michinomiya Hirohito",
      "Isoroku Yamamoto",
      "Fumimaro Konoe",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question:
      "In relation to the British Occupation in Ireland, what does the IRA stand for.",
    correctAnswer: "Irish Republican Army",
    incorrectAnswers: [
      "Irish Rebel Alliance",
      "Irish Reformation Army",
      "Irish-Royal Alliance",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question: "What event marked the start of World War II?",
    correctAnswer: "Invasion of Poland (1939)",
    incorrectAnswers: [
      "Invasion of Russia (1942)",
      "Battle of Britain (1940)",
      "Invasion of Normandy (1944)",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question:
      "Which U.S. president took part in the Potsdam Conference, where the Allies reached id: v4() peace settlement with Germany?",
    correctAnswer: "Harry S. Truman",
    incorrectAnswers: [
      "Dwight D. Eisenhower",
      "Franklin D. Roosevelt",
      "Herbert Hoover",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question:
      "Which of these founding fathers of the United States of America later became president?",
    correctAnswer: "James Monroe",
    incorrectAnswers: ["Alexander Hamilton", "Samuel Adams", "Roger Sherman"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question: "In what year did Texas secede from Mexico?",
    correctAnswer: "1836",
    incorrectAnswers: ["1838", "1845", "1844"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question:
      "What was the transfer of disease, crops, and people across the Atlantic shortly after the discovery of the Americas called?",
    correctAnswer: "The Columbian Exchange",
    incorrectAnswers: [
      "Triangle Trade",
      "Transatlantic Slave Trade",
      "The Silk Road",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question:
      "What was the bloodiest single-day battle during the American Civil War?",
    correctAnswer: "The Battle of Antietam",
    incorrectAnswers: [
      "The Siege of Vicksburg",
      "The Battle of Gettysburg",
      "The Battles of Chancellorsville",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question:
      "What is the name of the US Navy spy ship which was attacked and captured by North Korean forces in 1968?",
    correctAnswer: "USS Pueblo",
    incorrectAnswers: [
      "USS North Carolina",
      "USS Constitution",
      "USS Indianapolis",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question: "Under which name was Rodrigo Borgia made Pope?",
    correctAnswer: "Alexander VI",
    incorrectAnswers: ["Rodrigo I", "John Paul II", "Pius VII"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question: "What is the oldest US state?",
    correctAnswer: "Delaware",
    incorrectAnswers: ["Rhode Island", "Maine", "Virginia"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question: "The Thirty Years War ended with which treaty?",
    correctAnswer: "Peace of Westphalia",
    incorrectAnswers: [
      "Treaty of Versailles",
      "Treaty of Paris",
      "Peace of Prague",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question:
      "Who is attributed credit for recording the epic poem The Odyssey?",
    correctAnswer: "Homer",
    incorrectAnswers: ["Aristotle", "Odysseus", "Socrates"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question:
      "The crown of the Empire State Building was originally built for what purpose?",
    correctAnswer: "Airship Dock",
    incorrectAnswers: ["Lightning Rod", "Antennae", "Flag Pole"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question:
      "Which American civilization is the source of the belief that the world would end or drastically change on December 21st, 2012?",
    correctAnswer: "The Mayans",
    incorrectAnswers: ["The Incas", "The Aztecs", "The Navajos"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question: "In which year did the First World War begin?",
    correctAnswer: "1914",
    incorrectAnswers: ["1930", "1917", "1939"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question: "What year did the Vietnam War end?",
    correctAnswer: "1975",
    incorrectAnswers: ["1978", "1967", "1969"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question: "What was Genghis Khan&#039;s real name?",
    correctAnswer: "Tem&uuml;jin",
    incorrectAnswers: ["M&ouml;ngke", "&Ouml;gedei", "Tem&uuml;r"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question:
      "On which day did construction start on &quot;The Pentagon&quot;, the headquarters for the United States Department of Defense?",
    correctAnswer: "September 11, 1941",
    incorrectAnswers: [
      "June 15, 1947",
      "January 15, 1943",
      "September 2, 1962",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question:
      "America&#039;s Strategic Defense System during the Cold War was nicknamed after this famous movie.",
    correctAnswer: "Star Wars",
    incorrectAnswers: ["Jaws", "Blade Runner", "Alien"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[2].id,
    question: "Which of these facilities was not present on the Titanic?",
    correctAnswer: "Fainting room",
    incorrectAnswers: ["Turkish bath", "Kennel", "Squash court"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question: "When did Spanish Peninsular War start?",
    correctAnswer: "1808",
    incorrectAnswers: ["1806", "1810", "1809"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question:
      "Toussaint Louverture led a successful slave revolt in which country?",
    correctAnswer: "Haiti",
    incorrectAnswers: ["France", "Cuba", "United States"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question: "When did the French Revolution begin?",
    correctAnswer: "1789",
    incorrectAnswers: ["1823", "1756", "1799"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question:
      "When was the &quot;Siege of Leningrad&quot; lifted during World War II?",
    correctAnswer: "January 1944",
    incorrectAnswers: ["September 1943", "November 1943", "March 1944"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question:
      "Who was the President of the United States during the signing of the Gadsden Purchase?",
    correctAnswer: "Franklin Pierce",
    incorrectAnswers: ["Andrew Johnson", "Abraham Lincoln", "James Polk"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question:
      "What was the real name of the Albanian national leader Skanderbeg?",
    correctAnswer: "Gjergj Kastrioti",
    incorrectAnswers: ["Diturak Zhulati", "Iskander Bejko", "Mirash Krasniki"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question:
      "During World War I, which nation&#039;s monarchs were blood related?",
    correctAnswer: "England, Germany, Russia",
    incorrectAnswers: [
      "France, Russia, Germany",
      "Serbia, Russia, Croatia",
      "Germany, Spain, Austria",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question:
      "What is the name of the Boeing B-29 that dropped the &#039;Little Boy&#039; atomic bomb on Hiroshima?",
    correctAnswer: "Enola Gay",
    incorrectAnswers: ["Necessary Evil", "The Great Artiste", "Full House"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question:
      "During the Spanish Civil War (1936), Francisco Franco fought for which political faction?",
    correctAnswer: "Nationalist Spain",
    incorrectAnswers: ["Republican Spain", "Popular Front", "Papal State"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question: "What was Napoleon Bonaparte&#039;s name before he changed it?",
    correctAnswer: "Napoleone di Buonaparte",
    incorrectAnswers: [
      "Naapolion van Bonijpaart",
      "Napole&atilde;o do Boaparte",
      "Napoleona de Buenoparte",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question:
      "The main objective of the German operation &quot;Case Blue&quot; during World War II was originally to capture what?",
    correctAnswer: "Caucasus",
    incorrectAnswers: ["Stalingrad", "Crimea", "Voronezh"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question: "When was the SS or Schutzstaffel established?",
    correctAnswer: "April 4th, 1925",
    incorrectAnswers: [
      "September 1st, 1941",
      "March 8th, 1935",
      "February 21st, 1926",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question:
      "Which of these theoretical phycisists first predicted the existence of antimatter?",
    correctAnswer: "Paul Dirac",
    incorrectAnswers: ["Niels Bohr", "Albert Einstein", "Werner Heisenberg"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question:
      "How many women joined the United States Armed Services during World War II?",
    correctAnswer: "350,000",
    incorrectAnswers: ["225,000", "100,000", "500,000"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question:
      "In addition to his career as an astrologer and &quot;prophet&quot;, Nostradamus published a 1555 treatise that included a section on what?",
    correctAnswer: "Making jams and jellies",
    incorrectAnswers: [
      "Teaching parrots to talk",
      "Cheating at card games",
      "Digging graves",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question: "The pantheon in Rome was used to worship what god?",
    correctAnswer: "Any god they wanted",
    incorrectAnswers: ["Athena", "Zeus", "Both Athena and Zeus"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question: "The Battle of Hastings was fought in which year?",
    correctAnswer: "1066",
    incorrectAnswers: ["911", "1204", "1420"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question:
      "What was the name of the spy ring that helped the United States win the Revolutionary War?",
    correctAnswer: "Culper Ring",
    incorrectAnswers: [
      "New York Spy Ring",
      "Washington&#039;s Spies",
      "Unnamed",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question:
      "Which of the following physicists did NOT work on the Manhattan project?",
    correctAnswer: "Murray Gell-Mann",
    incorrectAnswers: [
      "Richard Feynman",
      "J. Robert Oppenheimer",
      "John Von-Neumann",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[2].id,
    question:
      "The Bohemian Revolt (1618-1620) started after Protestants in Prague did what to their Catholic Lords Regents?",
    correctAnswer: "Threw them out of a window",
    incorrectAnswers: [
      "Insulted their mothers",
      "Locked them in stockades",
      "Hung them.",
    ],
  },
 
  // GEOGRAPHY
 
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question: "What country has a horizontal bicolor red and white flag?",
    correctAnswer: "Monaco",
    incorrectAnswers: ["Bahrain", "Malta", "Liechenstein"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question: "Harvard University is located in which city?",
    correctAnswer: "Cambridge",
    incorrectAnswers: ["Providence", "New York", "Washington D.C."],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question: "How many time zones does China have?",
    correctAnswer: "1",
    incorrectAnswers: ["3", "4", "2"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question:
      "Which of the following languages does NOT use the Latin alphabet?",
    correctAnswer: "Georgian",
    incorrectAnswers: ["Turkish", "Swahili", "Vietnamese"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question: "How many countries does Mexico border?",
    correctAnswer: "3",
    incorrectAnswers: ["2", "4", "1"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question: "The Space Needle is located in which city?",
    correctAnswer: "Seattle",
    incorrectAnswers: ["Los Angles", "Toronto", "Vancouver"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question: "The body of the Egyptian Sphinx was based on which animal?",
    correctAnswer: "Lion",
    incorrectAnswers: ["Bull", "Horse", "Dog"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question: "Which of the following former Yugoslavian states is landlocked?",
    correctAnswer: "Serbia",
    incorrectAnswers: ["Bosnia and Herzegovina", "Montenegro", "Croatia"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question: "Which country does Austria not border?",
    correctAnswer: "France",
    incorrectAnswers: ["Slovenia", "Switzerland", "Slovakia"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question:
      "Which of these is the name of the largest city in the US state Tennessee?",
    correctAnswer: "Memphis",
    incorrectAnswers: ["Thebes", "Alexandria", "Luxor"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question:
      "The derisive acronym &quot;PIIGS&quot; refers to which of the following European countries and their economic statuses?",
    correctAnswer: "Portugal, Ireland, Italy, Greece, Spain",
    incorrectAnswers: [
      "Poland, Iceland, Italy, Greece, Serbia",
      "Poland, Iceland, Italy, Greenland, Spain",
      "Portugal, Iceland, Ireland, Greece, Serbia",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question: "What is the Polish city known to Germans as Danzig?",
    correctAnswer: "Gdańsk",
    incorrectAnswers: ["Warsaw", "Zakopane", "Poznań"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question: "What is the name of New Zealand&#039;s indigenous people?",
    correctAnswer: "Maori",
    incorrectAnswers: ["Vikings", "Polynesians", "Samoans"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question:
      "All of the following are classified as Finno-Ugric languages EXCEPT:",
    correctAnswer: "Samoyedic",
    incorrectAnswers: ["Hungarian", "Finnish", "Estonian"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question:
      "Which of these African countries list &quot;Spanish&quot; as an official language?",
    correctAnswer: "Equatorial Guinea",
    incorrectAnswers: ["Guinea", "Cameroon", "Angola"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question:
      "What name was historically used for the Turkish city currently known as Istanbul?",
    correctAnswer: "Constantinople",
    incorrectAnswers: ["H&uuml;davendigar", "S&ouml;ğ&uuml;t", "Adrianople"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question: "What is the 15th letter of the Greek alphabet?",
    correctAnswer: "Omicron (&Omicron;)",
    incorrectAnswers: ["Sigma (&Sigma;)", "Pi (&Pi;)", "Nu (&Nu;)"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question: "What is the capital of Spain?",
    correctAnswer: "Madrid",
    incorrectAnswers: ["Barcelona", "Sevilla", "Toledo"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question: "Which of the following Japanese islands is the biggest?",
    correctAnswer: "Honshu",
    incorrectAnswers: ["Hokkaido", "Shikoku", "Kyushu"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[1].id,
    question:
      "Which of the following countries has a flag featuring a yellow lion wielding a sword on a dark red background?",
    correctAnswer: "Sri Lanka",
    incorrectAnswers: ["Kiribati", "Scotland", "Bhutan"],
  },
 
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question: "The land mass of modern day Turkey is called what?",
    correctAnswer: "Anatolia",
    incorrectAnswers: ["Ismuth of Ottoma", "Ottoma", "Ismuth of Anatolia"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question: "What is the capital of Greenland?",
    correctAnswer: "Nuuk",
    incorrectAnswers: ["Sisimiut", "Narsaq", "Maniitsoq"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question: "How many countries are inside the United Kingdom?",
    correctAnswer: "Four",
    incorrectAnswers: ["Two", "Three", "One"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question:
      "Which of these countries is &quot;doubly landlocked&quot; (surrounded entirely by one or more landlocked countries)?",
    correctAnswer: "Uzbekistan",
    incorrectAnswers: ["Switzerland", "Bolivia", "Ethiopia"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question: "The land of Gotland is located in which European country?",
    correctAnswer: "Sweden",
    incorrectAnswers: ["Denmark", "Norway", "Germany"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question: "What is the smallest country in South America by area?",
    correctAnswer: "Suriname",
    incorrectAnswers: ["Brazil", "Uruguay", "Chile"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question: "Where is Hadrian&#039;s Wall located?",
    correctAnswer: "Carlisle, England",
    incorrectAnswers: ["Rome, Italy", "Alexandria, Egypt", "Dublin, Ireland"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question: "Which of the following is the longest river in Europe?",
    correctAnswer: "Volga",
    incorrectAnswers: ["Danube", "Ural", "Dnieper"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question: "What city  has the busiest airport in the world?",
    correctAnswer: "Atlanta, Georgia USA",
    incorrectAnswers: [
      "London, England",
      "Chicago,Illinois ISA",
      "Tokyo,Japan",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question: "How many sovereign states are members of the United Nations?",
    correctAnswer: "195",
    incorrectAnswers: ["201", "153", "178"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question: "What is the capital of Australia?",
    correctAnswer: "Canberra",
    incorrectAnswers: ["Sydney", "Melbourne", "Brisbane"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question: "What is the longest river in Europe?",
    correctAnswer: "Volga",
    incorrectAnswers: ["Danube", "Rhine", "Thames"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question: "What is the largest non-continental island in the world?",
    correctAnswer: "Greenland",
    incorrectAnswers: ["New Guinea", "Borneo", "Madagascar"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question:
      "Which two modern-day countries used to be known as the region of Rhodesia between the 1890s and 1980?",
    correctAnswer: "Zambia &amp; Zimbabwe",
    incorrectAnswers: [
      "Togo &amp; Benin",
      "Lesotho &amp; Swaziland",
      "Rwanda &amp; Burundi",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question:
      "The Principality of Sealand is an unrecognized micronation off the coast of what country?",
    correctAnswer: "The United Kingdom",
    incorrectAnswers: ["Japan", "Austrailia", "Argentina"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question: "Which of these Japanese islands is the largest by area?",
    correctAnswer: "Shikoku",
    incorrectAnswers: ["Iki", "Odaiba", "Okinawa"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question: "Where is the &quot;Sonoran Desert&quot; located?",
    correctAnswer: "North America",
    incorrectAnswers: ["South America", "Asia", "Africa"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question: "Broome is a town in which state of Australia?",
    correctAnswer: "Western Australia",
    incorrectAnswers: ["Northern Territory", "South Australia", "Tasmania"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question:
      "Which of the following language families is the most controversial amongst modern linguists?",
    correctAnswer: "Altaic",
    incorrectAnswers: ["Sino-Tibetan", "Dravidian", "Indo-European"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[1].id,
    question:
      "Which of the following is not a megadiverse country - one that harbors a high number of the earth&#039;s endemic species?",
    correctAnswer: "Thailand",
    incorrectAnswers: ["Peru", "Mexico", "South Africa"],
  },
 
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question:
      "What is the name of rocky region that spans most of eastern Canada?",
    correctAnswer: "Canadian Shield",
    incorrectAnswers: [
      "Rocky Mountains",
      "Appalachian Mountains",
      "Himalayas",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question: "Into which basin does the Jordan River flow into?",
    correctAnswer: "Dead Sea",
    incorrectAnswers: ["Aral Sea", "Caspian Sea", "Salton Sea"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question: "Which is the largest freshwater lake in the world?",
    correctAnswer: "Lake Superior ",
    incorrectAnswers: ["Caspian Sea", "Lake Michigan", "Lake Huron"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question:
      "Bir Tawil, an uninhabited track of land claimed by no country, is located along the border of which two countries?",
    correctAnswer: "Egypt and Sudan",
    incorrectAnswers: [
      "Israel and Jordan",
      "Chad and Libya",
      "Iraq and Saudi Arabia",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question:
      "Which of the following Inuit languages was the FIRST to use a unique writing system not based on the Latin alphabet?",
    correctAnswer: "Inuktitut",
    incorrectAnswers: ["Inuinnaqtun", "Greenlandic", "Inupiat"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question:
      "In 2012 the German-speaking microstate &quot;Liechtenstein&quot; in Central Europe had a population of how many inhabitants?",
    correctAnswer: "36,600",
    incorrectAnswers: ["2,400", "90,000", "323,400"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question: "What country is not a part of Scandinavia?",
    correctAnswer: "Finland",
    incorrectAnswers: ["Norway", "Sweden", "Denmark"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question:
      "What is the name of the formerly rich fishing grounds off the island of Newfoundland, Canada?",
    correctAnswer: "Grand Banks",
    incorrectAnswers: ["Great Barrier Reef", "Mariana Trench", "Hudson Bay"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question: "What is Canada&#039;s largest island?",
    correctAnswer: "Baffin Island",
    incorrectAnswers: [
      "Prince Edward Island",
      "Vancouver Island",
      "Newfoundland",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question: "Which of these is NOT a province in China?",
    correctAnswer: "Yangtze",
    incorrectAnswers: ["Fujian", "Sichuan", "Guangdong"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question: "Which of these cities is NOT in England?",
    correctAnswer: "Edinburgh",
    incorrectAnswers: ["Oxford", "Manchester", "Southampton"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question: "When does Finland celebrate their independence day?",
    correctAnswer: "December 6th",
    incorrectAnswers: ["January 2nd", "November 12th", "February 8th"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question: "Which country is completely landlocked by South Africa?",
    correctAnswer: "Lesotho",
    incorrectAnswers: ["Swaziland", "Botswana", "Zimbabwe"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question: "Which country is the Taedong River in?",
    correctAnswer: "North Korea",
    incorrectAnswers: ["South Korea", "Japan", "China"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question: "What is the tallest mountain in Canada?",
    correctAnswer: "Mount Logan",
    incorrectAnswers: ["Mont Tremblant", "Whistler Mountain", "Blue Mountain"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question: "What national museum will you find in Cooperstown, New York?",
    correctAnswer: "National Baseball Hall of Fame",
    incorrectAnswers: [
      "Metropolitan Museum of Art",
      "National Toy Hall of Fame",
      "Museum of Modern Art",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question: "What is the land connecting North America and South America?",
    correctAnswer: "Isthmus of Panama",
    incorrectAnswers: ["Isthmus of Suez", "Urals", "Australasia"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question: "In which country is Tallinn located?",
    correctAnswer: "Estonia",
    incorrectAnswers: ["Finland", "Sweden", "Poland"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question:
      "What North American tourist attraction is served by the &quot;Maid of the Mist&quot; tour company?",
    correctAnswer: "Niagara Falls",
    incorrectAnswers: [
      "Whistler, British Columbia",
      "Disney World",
      "Yosemite National Park",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[1].id,
    question:
      "The mountainous Khyber Pass connects which of the two following countries?",
    correctAnswer: "Afghanistan and Pakistan",
    incorrectAnswers: [
      "India and Nepal",
      "Pakistan and India",
      "Tajikistan and Kyrgyzstan",
    ],
  },
 
  // SPORTS
 
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question: "In what sport is a &quot;shuttlecock&quot; used?",
    correctAnswer: "Badminton",
    incorrectAnswers: ["Table Tennis", "Rugby", "Cricket"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question: "Which player holds the NHL record of 2,857 points?",
    correctAnswer: "Wayne Gretzky",
    incorrectAnswers: ["Mario Lemieux ", "Sidney Crosby", "Gordie Howe"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question:
      "In Baseball, how many times does the ball have to be pitched outside of the strike zone before the batter is walked?",
    correctAnswer: "4",
    incorrectAnswers: ["1", "2", "3"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question:
      "How many soccer players should be on the field at the same time?",
    correctAnswer: "22",
    incorrectAnswers: ["20", "24", "26"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question: "Which team has won the most Stanley Cups in the NHL?",
    correctAnswer: "Montreal Canadians",
    incorrectAnswers: [
      "Chicago Blackhawks",
      "Toronto Maple Leafs",
      "Detroit Red Wings",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question: "Who won the 2017 Formula One World Drivers&#039; Championship?",
    correctAnswer: "Lewis Hamilton",
    incorrectAnswers: ["Sebastian Vettel", "Nico Rosberg", "Max Verstappen"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question:
      "Which year did Jenson Button won his first ever Formula One World Drivers&#039; Championship?",
    correctAnswer: "2009",
    incorrectAnswers: ["2010", "2007", "2006"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question: "What team won the 2016 MLS Cup?",
    correctAnswer: "Seattle Sounders",
    incorrectAnswers: ["Colorado Rapids", "Toronto FC", "Montreal Impact"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question: "Who won the 2016 Formula 1 World Driver&#039;s Championship?",
    correctAnswer: "Nico Rosberg",
    incorrectAnswers: ["Lewis Hamilton", "Max Verstappen", "Kimi Raikkonen"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question:
      "In the 2014 FIFA World Cup, what was the final score in the match Brazil - Germany?",
    correctAnswer: "1-7",
    incorrectAnswers: ["1-5", "1-6", "2-6"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question: "Who won the UEFA Champions League in 2016?",
    correctAnswer: "Real Madrid C.F.",
    incorrectAnswers: [
      "FC Bayern Munich",
      "Atletico Madrid",
      "Manchester City F.C.",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question: "When was the first official international game played?",
    correctAnswer: "1872",
    incorrectAnswers: ["1880", "1863", "1865"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question: "Which two teams played in Super Bowl XLII?",
    correctAnswer: "The New York Giants &amp; The New England Patriots",
    incorrectAnswers: [
      "The Green Bay Packers &amp; The Pittsburgh Steelers",
      "The Philadelphia Eagles &amp; The New England Patriots",
      "The Seattle Seahawks &amp; The Denver Broncos",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question:
      "Which boxer was banned for taking a bite out of Evander Holyfield&#039;s ear in 1997?",
    correctAnswer: "Mike Tyson",
    incorrectAnswers: ["Roy Jones Jr.", "Evander Holyfield", "Lennox Lewis"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question: "How many points did LeBron James score in his first NBA game?",
    correctAnswer: "25",
    incorrectAnswers: ["19", "69", "41"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question:
      "This Canadian television ebd55196-e115-4813-be1e-2314d95dd0d7caster is known for his &quot;Hockey Night in Canada&quot; role, a commentary show during hockey games.",
    correctAnswer: "Don Cherry",
    incorrectAnswers: ["Don McKellar", "Don Taylor ", "Donald Sutherland"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question:
      "Which English football club has the nickname &#039;The Foxes&#039;?",
    correctAnswer: "Leicester City",
    incorrectAnswers: [
      "Northampton Town",
      "Bradford City",
      "West Bromwich Albion",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question: "When was the FC Schalke 04 founded?",
    correctAnswer: "1904",
    incorrectAnswers: ["1909", "2008", "1999"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question:
      "What was the final score of the Germany vs. Brazil 2014 FIFA World Cup match?",
    correctAnswer: "7 - 1",
    incorrectAnswers: ["0 - 1", "3 - 4", "16 - 0"],
  },
  {
    id: v4(),
    difficultyId: difficulty[0].id,
    categoryId: categories[0].id,
    question:
      "Who won the premier league title in the 2015-2016 season following a fairy tale run?",
    correctAnswer: "Leicester City",
    incorrectAnswers: ["Tottenham Hotspur", "Watford", "Stoke City"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question: "In a game of snooker, what colour ball is worth 3 points?",
    correctAnswer: "Green",
    incorrectAnswers: ["Yellow", "Brown", "Blue"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question: "Why was The Green Monster at Fenway Park was originally built?",
    correctAnswer: "To prevent viewing games from outside the park.",
    incorrectAnswers: [
      "To make getting home runs harder.",
      "To display advertisements.",
      "To provide extra seating.",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question:
      "Who was the British professional wrestler Shirley Crabtree better known as?",
    correctAnswer: "Big Daddy",
    incorrectAnswers: ["Giant Haystacks", "Kendo Nagasaki", "Masambula"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question:
      "Which sport is NOT traditionally played during the Mongolian Naadam festival?",
    correctAnswer: "American Football",
    incorrectAnswers: ["Wrestling", "Archery", "Horse-Racing"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question:
      "At which bridge does the annual Oxford and Cambridge boat race start?",
    correctAnswer: "Putney",
    incorrectAnswers: ["Hammersmith", "Vauxhall ", "Battersea"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question:
      "Which portuguese island is soccer player Cristiano Ronaldo from?",
    correctAnswer: "Madeira",
    incorrectAnswers: ["Terceira", "Santa Maria", "Porto Santo"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question: "Who won the 2011 Stanley Cup?",
    correctAnswer: "Boston Bruins",
    incorrectAnswers: [
      "Montreal Canadiens",
      "New York Rangers",
      "Toronto Maple Leafs",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question:
      "What is the nickname of Northampton town&#039;s rugby union club?",
    correctAnswer: "Saints",
    incorrectAnswers: ["Harlequins", "Saracens", "Wasps"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question: "Which car manufacturer won the 2017 24 Hours of Le Mans?",
    correctAnswer: "Porsche",
    incorrectAnswers: ["Toyota", "Audi", "Chevrolet"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question: "Which team was the 2014-2015 NBA Champions?",
    correctAnswer: "Golden State Warriors",
    incorrectAnswers: [
      "Cleveland Cavaliers",
      "Houston Rockets",
      "Atlanta Hawks",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question: "Josh Mansour is part of what NRL team?",
    correctAnswer: "Penrith Panthers",
    incorrectAnswers: [
      "Melbourne Storm",
      "Sydney Roosters",
      "North Queensland Cowboys",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question: "What is the oldest team in Major League Baseball?",
    correctAnswer: "Atlanta Braves",
    incorrectAnswers: [
      "Chicago Cubs",
      "Cincinnati Reds",
      "St. Louis Cardinals",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question:
      "What is the name of the AHL affiliate of the Toronto Maple Leafs?",
    correctAnswer: "Toronto Marlies",
    incorrectAnswers: [
      "Toronto Rock",
      "Toronto Argonauts",
      "Toronto Wolfpack",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question: "What year was hockey legend Wayne Gretzky born?",
    correctAnswer: "1961",
    incorrectAnswers: ["1965", "1959", "1963"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question:
      "Which Formula 1 driver switched teams in the middle of the 2017 season?",
    correctAnswer: "Carlos Sainz Jr.",
    incorrectAnswers: ["Daniil Kvyat", "Jolyon Palmer", "Rio Haryanto"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question: "Which country is hosting the 2022 FIFA World Cup?",
    correctAnswer: "Qatar",
    incorrectAnswers: ["Uganda", "Vietnam", "Bolivia"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question:
      "Which NBA player has the most games played over the course of their career?",
    correctAnswer: "Robert Parish",
    incorrectAnswers: ["Kareem Abdul-Jabbar", "Kevin Garnett", "Kobe Bryant"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question: "A stimpmeter measures the speed of a ball over what surface?",
    correctAnswer: "Golf Putting Green",
    incorrectAnswers: [" Football Pitch", "Cricket Outfield", "Pinball Table"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question:
      "Which of the following pitchers was named National League Rookie of the Year for the 2013 season?",
    correctAnswer: "Jose Fernandez",
    incorrectAnswers: ["Jacob deGrom", "Shelby Miller", "Matt Harvey"],
  },
  {
    id: v4(),
    difficultyId: difficulty[1].id,
    categoryId: categories[0].id,
    question:
      "Which NBA player won Most Valuable Player for the 1999-2000 season?",
    correctAnswer: "Shaquille O&#039;Neal",
    incorrectAnswers: ["Allen Iverson", "Kobe Bryant", "Paul Pierce"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question:
      "Which of these Russian cities did NOT contain a stadium that was used in the 2018 FIFA World Cup?",
    correctAnswer: "Vladivostok",
    incorrectAnswers: ["Rostov-on-Don", "Yekaterinburg", "Kaliningrad"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question: "Which year was the third Super Bowl held?",
    correctAnswer: "1969",
    incorrectAnswers: ["1968", "1971", "1970"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question:
      "What is the full name of the footballer &quot;Cristiano Ronaldo&quot;?",
    correctAnswer: "Cristiano Ronaldo dos Santos Aveiro",
    incorrectAnswers: [
      "Cristiano Ronaldo los Santos Diego",
      "Cristiano Armando Diego Ronaldo",
      "Cristiano Luis Armando Ronaldo",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question:
      "Which player &quot;kung-fu kicked&quot; a Crystal Palace fan in January 1995?",
    correctAnswer: "Eric Cantona",
    incorrectAnswers: ["David Seamen", "Ashley Cole", "Mark Hughes"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question:
      "Which female player won the gold medal of table tennis singles in 2016 Olympics Games?",
    correctAnswer: "DING Ning (China)",
    incorrectAnswers: [
      "LI Xiaoxia (China)",
      "Ai FUKUHARA (Japan)",
      "Song KIM (North Korea)",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question: "What is &ldquo;The Sport of Kings&rdquo;?",
    correctAnswer: "Horse Racing",
    incorrectAnswers: ["Chess", "Jousting", "Fencing"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question:
      "What tool lends it&#039;s name to a last-stone advantage in an end in Curling?",
    correctAnswer: "Hammer",
    incorrectAnswers: ["Wrench", "Drill", "Screwdriver"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question:
      "What team did England beat in the semi-final stage to win in the 1966 World Cup final?",
    correctAnswer: "Portugal",
    incorrectAnswers: ["West Germany", "Soviet Union", "Brazil"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question:
      "Which car company is the only Japanese company which won the 24 Hours of Le Mans?",
    correctAnswer: "Mazda",
    incorrectAnswers: ["Toyota", "Subaru", "Nissan"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question:
      "Which city features all of their professional sports teams&#039; jersey&#039;s with the same color scheme?",
    correctAnswer: "Pittsburgh",
    incorrectAnswers: ["New York", "Seattle", "Tampa Bay"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question: "Where was the Games of the XXII Olympiad held?",
    correctAnswer: "Moscow",
    incorrectAnswers: ["Barcelona", "Tokyo", "Los Angeles"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question:
      "Which English football team is nicknamed &#039;The Tigers&#039;?",
    correctAnswer: "Hull City",
    incorrectAnswers: ["Cardiff City", "Bristol City", "Manchester City"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question:
      "How many times did Martina Navratilova win the Wimbledon Singles Championship?",
    correctAnswer: "Nine",
    incorrectAnswers: ["Ten", "Seven", "Eight"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question: "With which doubles partner did John McEnroe have most success?",
    correctAnswer: "Peter Fleming",
    incorrectAnswers: ["Mark Woodforde", "Michael Stich", "Mary Carillo"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question: "Who is Manchester United&#039;s leading appearance maker?",
    correctAnswer: "Ryan Giggs",
    incorrectAnswers: ["David Beckham", "Wayne Rooney", "Eric Cantona"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question:
      "Which male player won the gold medal of table tennis singles in 2016 Olympics Games?",
    correctAnswer: "Ma Long (China)",
    incorrectAnswers: [
      "Zhang Jike (China)",
      "Jun Mizutani (Japan)",
      "Vladimir Samsonov (Belarus)",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question:
      "Which Italian footballer told Neuer where he&#039;s putting his shot and dragging it wide, during the match Italy-Germany, UEFA EURO 2016?",
    correctAnswer: "Pelle",
    incorrectAnswers: ["Insigne", "Barzagli", "Giaccherini"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question: "The AHL affiliate team of the Boston Bruins is named what?",
    correctAnswer: "Providence Bruins",
    incorrectAnswers: [
      "New Haven Bruins",
      "Cambridge Bruins",
      "Hartford Bruins",
    ],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question: "The Mazda 787B won the 24 Hours of Le Mans in what year?",
    correctAnswer: "1991",
    incorrectAnswers: ["1990", "2000", "1987"],
  },
  {
    id: v4(),
    difficultyId: difficulty[2].id,
    categoryId: categories[0].id,
    question: "In Canadian football, scoring a rouge is worth how many points?",
    correctAnswer: "1",
    incorrectAnswers: ["2", "3", "4"],
  },
];
 
 
module.exports = { questions, categories, difficulty };